---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: 'https://api.recollect.net/api/places/{{ place_id }}/services/1263/events?nomerge=1&hide=reminder_only&after={{ "now" | date: "%Y-%m-%d" }}&before={{ "now" | date: "%s" | plus: 2592000 | date: "%Y-%m-%d" }}&locale=en'
polling_headers: user-agent=TRMNL-Nashville-Waste/1.0
polling_body: ''
id: 240532
custom_fields:
- keyname: author_bio
  name: About This Plugin
  field_type: author_bio
  category: life,environment
  description: Show the next pickup date for Nashville Waste Services. Forked from <a href="https://github.com/hossain-khan/trmnl-next-pickup-plugin" class="underline">Hossain Khan's Next Pickup Plugin</a>
  github_url: https://github.com/stephenyeargin/trmnl-nashville-waste-services
  email_address: stephen@yearg.in
  learn_more_url: https://www.nashville.gov/departments/waste-services/trash-and-recycling-services/recycling-app
- keyname: place_id
  field_type: string
  name: Place ID
  description: Your unique location ID from Recollect. Look at the <a href="https://www.nashville.gov/departments/waste-services/trash-and-recycling-services/recycling-app">URL for exporting an ICS calendar</a>.
  placeholder: 918DB048-D91A-11E8-B83E-68F5AF88FEB0
name: Nashville Waste Collection
refresh_interval: 1440
